### ISSUE TITLE
(conda R) clang-4.0: error: linker command failed with exit code 1

### ISSUE THREAD

**Issue by rdrr1990** [coatless/r-macos-clang#8]
Hi @coatless ,

I recently used the `r-macos-os` `pkg installer` (which is wonderful and greatly expedited getting `bigKRLS 2.0.0` up on `CRAN`). I was recently brought on a project that uses `Anaconda` to version control its `R` packages. Using `R 3.4.1` on `MacOS Sierra`, 
```
which(R)
/Users/mohanty/anaconda/bin/R
```
For example, `install.packages("Hmisc")` downloads and decompresses some files; this is the first error:

```
ld: library not found for -lintl
clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [checkmate.so] Error 1
ERROR: compilation failed for package ‘checkmate’
```
Ultimately, it fails to install (`non-zero exit status`). 

I tried the following without luck:

```
mkdir  /Users/mohanty/anaconda/lib/R/R/
cat <<- EOF > /Users/mohanty/anaconda/lib/R/R/Makevars
# The following statements are required to use the clang4 binary
CC=/usr/local/clang4/bin/clang
CXX=/usr/local/clang4/bin/clang++
CXX1X=/usr/local/clang4/bin/clang++
CXX98=/usr/local/clang4/bin/clang++
CXX11=/usr/local/clang4/bin/clang++
CXX14=/usr/local/clang4/bin/clang++
CXX17=/usr/local/clang4/bin/clang++
LDFLAGS=-L/usr/local/clang4/lib
# End clang4 inclusion statements
EOF
```

Is there a way to run the installer so that it focuses on this `conda` copy of `R`?  

Many thanks,
Pete

**Comment by coatless** [comment]
Greetings and Salutations @rdrr1990,

`conda` is a special kind of beast since its support with compiled code is flaky. The flakiness comes from it breaking so much of the established R binary pathing locations. This has been ongoing for a while... c.f. 

- [SO: anaconda-r-rcpp-error](https://stackoverflow.com/questions/39604275/anaconda-r-rcpp-error)
- [Anaconda UG: Can't install packages in conda installed R](https://groups.google.com/a/continuum.io/forum/#!msg/anaconda/rKsQM1xhUjk/aklrzTodAgAJ)

As a result, I do not have an immediate response as to what's up. I'll need to look at _how_ the `conda` package ships _R_. This means I need to figure out:

- Does `~/.R/Makevars` get read by the `conda` shipped with `R`?
- What kind of compiler does `conda` ship with? 
    - e.g. Does it use a system compiler ala XCode CLI or the custom toolchain?
- Does switching support from the `conda` toolchain affect how packages can be managed?
    - e.g. Will there be any kind of ABI breakage?


For any kind of package development, I would seriously suggest not using the `conda` version of _R_. I presently manage my dev stack via `brew`, `brew cask` (for installers), and an `install.packages()` script. 

Sorry I cannot provide a better response at the moment.

**Comment by rdrr1990** [comment]
Very understandable. I don't plan to use this for development. I didn't notice any difference in behavior when I created the `Makevars` file so it may well not be being read. I will look into the resources you posted and see if I can provide any useful details.

**Comment by coatless** [comment]
@rdrr1990 Long time in the making, but the long story short is `conda` has its own compile infrastructure. Details can be found at: https://conda.io/docs/user-guide/tasks/build-packages/compiler-tools.html

In terms of compiling under `conda`'s _R_ installation, you will need to run:

```bash
conda install -y clang_osx-64 clangxx_osx-64 gfortran_osx-64
```

**Comment by rdrr1990** [comment]
thanks for chasing this down!
